# rsyslog server - простой вариант для лабораторных

module(load="imudp")
input(type="imudp" port="514")

template(name="RemoteLogs" type="string"
         string="/var/log/remote/%HOSTNAME%/%PROGRAMNAME%.log")

*.* ?RemoteLogs
& stop