module(load="imuxsock")
module(load="imklog")
module(load="omfwd")

*.* action(
  type="omfwd"
  target="@@RSYSLOG_SERVER@@"
  port="6514"
  protocol="tcp"
  StreamDriver="gtls"
  StreamDriverMode="1"
  StreamDriverAuthMode="anon"
)